<?php
/**
 * Created by PhpStorm.
 * User: Jimersy Lee
 * Date: 2017/5/27
 * Time: 14:45
 */
namespace Framework;

use Framework\Di\Injectable;

class App extends Injectable {

    /**
     * 依赖注入管理器
     * @var
     */
    protected $_dependencyInjector;


    /**
     * 事件管理器
     * @var
     */
    protected $_eventsManager;

    /**
     * App constructor.
     */
    public function __construct($di)
    {
        parent::setDI($di);
    }


    public function getDI()
    {
        return parent::getDI(); // TODO: Change the autogenerated stub
    }


    /**
     * 处理请求
     */
    public function handle(){



    }



}